# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dcb530e2bb99f943b4d4c565be90d32729041068c6ff02f56740365cf56a4e79d25ea3454fa7e6c27e2cfa1d90532ec31cfb5542d080220037eb95aa1e34e08a

test:
  secret_key_base: 5225fd3fd1d1035336c717a74e02a2e38c6fc0033e10c408388fdeca983adc261ff479be05019786077f6b4be9cfb3c8d8f1df4fcc2f52acde56666980f45092

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
